### PR TITLE
Improved V2 Docs

### PR DESCRIPTION
**Pull request by DJN1**
Hey, I spent some time fixing some typos and sentences. I also added some details and rephrased some things. Let me know if there are any issues!

### CODE REVIEW

**Comment by DJN1** [comment]
@marc2332

**Comment by marc2332** [comment]
> @marc2332 

I didnt see the notification sorry, I will review it ASAP

**Comment by DJN1** [comment]
No worries, I just wanted to make sure you see it.

**Comment by marc2332** [comment]
Looks good to me! Thank you very much. I really appreciate this ! 😄

**Pull request merged**
